export const STATE_FETCH_SUCCESS = 'STATE_FETCH_SUCCESS';
export const STATE_FETCH_FAILED = 'STATE_FETCH_FAILED'
export const PARTICULAR_STATE_SUCCESS = 'PARTICULAR_STATE_SUCCESS'
export const PARTICULAR_STATE_FAILED = 'PARTICULAR_STATE_FAILED'

export const DETAILS_FETCH_SUCCESS = 'DETAILS_FETCH_SUCCESS';
export const DETAILS_FETCH_FAILED = 'DETAILS_FETCH_FAILED';
export const PARTICULAR_DETAILS_SUCCESS = 'PARTICULAR_DETAILS_SUCCESS';
export const PARTICULAR_DETAILS_FAILED = 'PARTICULAR_DETAILS_FAILED';
export const DETAILS_DANGER_SUCCESS = 'DETAILS_DANGER_SUCCESS'
export const DETAILS_DANGER_FAILED = 'DETAILS_DANGER_FAILED'
export const DETAIL_BY_ID_SUCCESS = 'DETAIL_BY_ID_SUCCESS'
export const DETAIL_BY_ID_FAIL = 'DETAIL_BY_ID_FAIL'


export const DRUG_FETCH_SUCCESS = 'DRUG_FETCH_SUCCESS';
export const DRUG_FETCH_FAILED = 'DRUG_FETCH_FAILED';
export const DRUG_BYID_SUCCESS = 'DRUG_BYID_SUCCESS'
export const DRUG_BYID_FAILED = 'DRUG_BYID_FAILED'
export const DRUG_ADD_SUCCESS = 'DRUG_ADD_SUCCESS'
export const DRUG_ADD_FAILED = 'DRUG_ADD_FAILED'

export const PROTEIN_ADD_SUCCESS = 'PROTEIN_ADD_SUCCESS';
export const PROTEIN_ADD_FAILED = 'PROTEIN_ADD_FAILED';
export const PROTEIN_FETCH_SUCCESS = 'PROTEIN_FETCH_SUCCESS';
export const PROTEIN_FETCH_FAILED = 'PROTEIN_FETCH_FAILED';
export const PROTEIN_ID_SUCCESS = 'PROTEIN_ID_SUCCESS';
export const PROTEIN_ID_FAILED = 'PROTEIN_ID_FAILED';

export const ADD_GENE_SUCCESS = 'ADD_GENE_SUCCESS';
export const ADD_GENE_FAILED = 'ADD_GENE_FAILED';
export const FETCH_GENE_SUCCESS = 'FETCH_GENE_SUCCESS';
export const FETCH_GENE_FAILED = 'FETCH_GENE_FAILED';
export const GENE_ID_SUCCESS = 'GENE_ID_SUCCESS'
export const GENE_ID_FAILED = 'GENE_ID_FAILED'

export const BIOMODEL_FETCH_SUCCESS = 'BIOMODEL_FETCH_SUCCESS'
export const BIOMODEL_FETCH_FAILED = 'BIOMODEL_FETCH_FAILED'
export const ACCESSION_ID_SUCCESS = 'ACCESSION_ID_SUCCESS'
export const ACCESSION_ID_FAILED = 'ACCESSION_ID_FAILED'
export const BIOMODEL_GENESYMBOL_SUCCESS = 'BIOMODEL_GENESYMBOL_SUCCESS'
export const BIOMODEL_GENESYMBOL_FAILED = 'BIOMODEL_GENESYMBOL_FAILED'
export const ADD_BIOMODEL_SUCCESS = 'ADD_BIOMODEL_SUCCESS'
export const ADD_BIOMODEL_FAILED = 'ADD_BIOMODEL_FAILED'

export const FILTER_PROTEIN = 'FILTER_PROTEIN'
export const CLEAR_FILTER = 'CLEAR_FILTER'

export const FILTER_DETAILS = 'FILTER_DETAILS'

export const FILTER_DRUGS = 'FILTER_DRUGS'

export const FILTER_BIOMODEL = 'FILTER_BIOMODEL'









